// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type Node struct {
	ID        int64     `json:"id"`
	User      string    `json:"user"`
	Host      string    `json:"host"`
	CreatedAt time.Time `json:"created_at"`
}
