CREATE TABLE nodes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user TEXT NOT NULL,
    host TEXT NOT NULL UNIQUE,
    host_key TEXT NOT NULL,
    identity_file TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
