CREATE TABLE deployments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    FOREIGN KEY target_host REFERENCES nodes(id),
    FOREIGN KEY build_host REFERENCES nodes(id),

    command TEXT NOT NULL,

    is_upgrade BOOLEAN NOT NULL DEFAULT FALSE,
    is_cancelled BOOLEAN NOT NULL DEFAULT FALSE,

    executed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
