// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package db

import (
	"context"
	"database/sql"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (target_node, build_node, action, config_file, command, is_upgrade, is_rollback)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, target_node, build_node, "action", config_file, command, is_upgrade, is_rollback, is_cancelled, exit_code, error, executed_at
`

type CreateDeploymentParams struct {
	TargetNode int64         `json:"target_node"`
	BuildNode  sql.NullInt64 `json:"build_node"`
	Action     string        `json:"action"`
	ConfigFile string        `json:"config_file"`
	Command    string        `json:"command"`
	IsUpgrade  bool          `json:"is_upgrade"`
	IsRollback bool          `json:"is_rollback"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.TargetNode,
		arg.BuildNode,
		arg.Action,
		arg.ConfigFile,
		arg.Command,
		arg.IsUpgrade,
		arg.IsRollback,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.TargetNode,
		&i.BuildNode,
		&i.Action,
		&i.ConfigFile,
		&i.Command,
		&i.IsUpgrade,
		&i.IsRollback,
		&i.IsCancelled,
		&i.ExitCode,
		&i.Error,
		&i.ExecutedAt,
	)
	return i, err
}

const finishDeployment = `-- name: FinishDeployment :exec
UPDATE deployments
SET exit_code = ?, error = ?, finished_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type FinishDeploymentParams struct {
	ExitCode int64  `json:"exit_code"`
	Error    string `json:"error"`
	ID       int64  `json:"id"`
}

func (q *Queries) FinishDeployment(ctx context.Context, arg FinishDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, finishDeployment, arg.ExitCode, arg.Error, arg.ID)
	return err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, target_node, build_node, "action", config_file, command, is_upgrade, is_rollback, is_cancelled, exit_code, error, executed_at FROM deployments WHERE id = ?
`

func (q *Queries) GetDeployment(ctx context.Context, id int64) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.TargetNode,
		&i.BuildNode,
		&i.Action,
		&i.ConfigFile,
		&i.Command,
		&i.IsUpgrade,
		&i.IsRollback,
		&i.IsCancelled,
		&i.ExitCode,
		&i.Error,
		&i.ExecutedAt,
	)
	return i, err
}

const listDeployments = `-- name: ListDeployments :many
SELECT id, target_node, build_node, "action", config_file, command, is_upgrade, is_rollback, is_cancelled, exit_code, error, executed_at FROM deployments
ORDER BY executed_at DESC, id DESC
LIMIT ?
`

func (q *Queries) ListDeployments(ctx context.Context, limit int64) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeployments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.TargetNode,
			&i.BuildNode,
			&i.Action,
			&i.ConfigFile,
			&i.Command,
			&i.IsUpgrade,
			&i.IsRollback,
			&i.IsCancelled,
			&i.ExitCode,
			&i.Error,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsForNode = `-- name: ListDeploymentsForNode :many
SELECT id, target_node, build_node, "action", config_file, command, is_upgrade, is_rollback, is_cancelled, exit_code, error, executed_at FROM deployments
WHERE target_node = ?
ORDER BY executed_at DESC, id DESC
LIMIT ?
`

type ListDeploymentsForNodeParams struct {
	TargetNode int64 `json:"target_node"`
	Limit      int64 `json:"limit"`
}

func (q *Queries) ListDeploymentsForNode(ctx context.Context, arg ListDeploymentsForNodeParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsForNode, arg.TargetNode, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.TargetNode,
			&i.BuildNode,
			&i.Action,
			&i.ConfigFile,
			&i.Command,
			&i.IsUpgrade,
			&i.IsRollback,
			&i.IsCancelled,
			&i.ExitCode,
			&i.Error,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCancelled = `-- name: SetCancelled :exec
UPDATE deployments SET is_cancelled = ? WHERE id = ?
`

type SetCancelledParams struct {
	IsCancelled bool  `json:"is_cancelled"`
	ID          int64 `json:"id"`
}

func (q *Queries) SetCancelled(ctx context.Context, arg SetCancelledParams) error {
	_, err := q.db.ExecContext(ctx, setCancelled, arg.IsCancelled, arg.ID)
	return err
}
