// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createNamedBlobLog = `-- name: CreateNamedBlobLog :one
INSERT INTO logs(level, logger_name, message, metadata)
VALUES(?, ?, ?, ?)
RETURNING id, timestamp, level, logger_name, message, json(metadata)
`

type CreateNamedBlobLogParams struct {
	Level      string          `json:"level"`
	LoggerName sql.NullString  `json:"logger_name"`
	Message    string          `json:"message"`
	Metadata   json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateNamedBlobLog(ctx context.Context, arg CreateNamedBlobLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createNamedBlobLog,
		arg.Level,
		arg.LoggerName,
		arg.Message,
		arg.Metadata,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Level,
		&i.LoggerName,
		&i.Message,
		&i.Metadata,
	)
	return i, err
}

const createNamedLog = `-- name: CreateNamedLog :one
INSERT INTO logs(level, logger_name, message)
VALUES(?, ?, ?)
RETURNING id, timestamp, level, logger_name, message, json(metadata)
`

type CreateNamedLogParams struct {
	Level      string         `json:"level"`
	LoggerName sql.NullString `json:"logger_name"`
	Message    string         `json:"message"`
}

func (q *Queries) CreateNamedLog(ctx context.Context, arg CreateNamedLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createNamedLog, arg.Level, arg.LoggerName, arg.Message)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Level,
		&i.LoggerName,
		&i.Message,
		&i.Metadata,
	)
	return i, err
}

const createUnnamedBlobLog = `-- name: CreateUnnamedBlobLog :one
INSERT INTO logs(level, message, metadata)
VALUES (?, ?, ?)
RETURNING id, timestamp, level, logger_name, message, json(metadata)
`

type CreateUnnamedBlobLogParams struct {
	Level    string          `json:"level"`
	Message  string          `json:"message"`
	Metadata json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateUnnamedBlobLog(ctx context.Context, arg CreateUnnamedBlobLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createUnnamedBlobLog, arg.Level, arg.Message, arg.Metadata)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Level,
		&i.LoggerName,
		&i.Message,
		&i.Metadata,
	)
	return i, err
}

const createUnnamedLog = `-- name: CreateUnnamedLog :one
INSERT INTO logs(level, message)
VALUES (?, ?)
RETURNING id, timestamp, level, logger_name, message, json(metadata)
`

type CreateUnnamedLogParams struct {
	Level   string `json:"level"`
	Message string `json:"message"`
}

func (q *Queries) CreateUnnamedLog(ctx context.Context, arg CreateUnnamedLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createUnnamedLog, arg.Level, arg.Message)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Level,
		&i.LoggerName,
		&i.Message,
		&i.Metadata,
	)
	return i, err
}
