// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs.sql

package db

import (
	"context"
	"encoding/json"
)

const createLog = `-- name: CreateLog :one
INSERT INTO logs(source, level, message, metadata)
VALUES(?, ?, ?, ?)
RETURNING id, timestamp, source, level, message, json(metadata)
`

type CreateLogParams struct {
	Source   string          `json:"source"`
	Level    string          `json:"level"`
	Message  string          `json:"message"`
	Metadata json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createLog,
		arg.Source,
		arg.Level,
		arg.Message,
		arg.Metadata,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Source,
		&i.Level,
		&i.Message,
		&i.Metadata,
	)
	return i, err
}

const getNLogs = `-- name: GetNLogs :many
SELECT id, timestamp, source, level, message, json(metadata) FROM logs
LIMIT ? OFFSET ?
`

type GetNLogsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetNLogs(ctx context.Context, arg GetNLogsParams) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, getNLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Source,
			&i.Level,
			&i.Message,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNLogsFromSource = `-- name: GetNLogsFromSource :many
SELECT id, timestamp, source, level, message, json(metadata) FROM logs
WHERE source = ?
LIMIT ? OFFSET ?
`

type GetNLogsFromSourceParams struct {
	Source string `json:"source"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) GetNLogsFromSource(ctx context.Context, arg GetNLogsFromSourceParams) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, getNLogsFromSource, arg.Source, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Source,
			&i.Level,
			&i.Message,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
