// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Cmd struct {
	ID         int64        `json:"id"`
	Foreign    interface{}  `json:"foreign"`
	IsUpgrade  sql.NullBool `json:"is_upgrade"`
	ExecutedAt time.Time    `json:"executed_at"`
}

type Log struct {
	ID        int64           `json:"id"`
	Timestamp time.Time       `json:"timestamp"`
	Source    string          `json:"source"`
	Level     string          `json:"level"`
	Message   string          `json:"message"`
	Metadata  json.RawMessage `json:"metadata"`
}

type Node struct {
	ID           int64     `json:"id"`
	User         string    `json:"user"`
	Host         string    `json:"host"`
	HostKey      string    `json:"host_key"`
	IdentityFile string    `json:"identity_file"`
	ConfigFile   string    `json:"config_file"`
	CreatedAt    time.Time `json:"created_at"`
}
