// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Deployment struct {
	ID          int64         `json:"id"`
	TargetNode  int64         `json:"target_node"`
	BuildNode   sql.NullInt64 `json:"build_node"`
	Action      string        `json:"action"`
	ConfigFile  string        `json:"config_file"`
	Command     string        `json:"command"`
	IsUpgrade   bool          `json:"is_upgrade"`
	IsRollback  bool          `json:"is_rollback"`
	IsCancelled bool          `json:"is_cancelled"`
	ExitCode    int64         `json:"exit_code"`
	Error       string        `json:"error"`
	ExecutedAt  time.Time     `json:"executed_at"`
}

type Log struct {
	ID        int64           `json:"id"`
	Timestamp time.Time       `json:"timestamp"`
	Source    string          `json:"source"`
	Level     string          `json:"level"`
	Message   string          `json:"message"`
	Metadata  json.RawMessage `json:"metadata"`
}

type Node struct {
	ID           int64     `json:"id"`
	User         string    `json:"user"`
	Host         string    `json:"host"`
	HostKey      string    `json:"host_key"`
	IdentityFile string    `json:"identity_file"`
	ConfigFile   string    `json:"config_file"`
	CreatedAt    time.Time `json:"created_at"`
}
