// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package db

import (
	"context"
)

const countNodes = `-- name: CountNodes :one
SELECT COUNT(DISTINCT host) FROM nodes
`

func (q *Queries) CountNodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (user, host, host_key, identity_file)
VALUES (?, ?, ?, ?)
RETURNING id, user, host, host_key, identity_file, created_at
`

type CreateNodeParams struct {
	User         string `json:"user"`
	Host         string `json:"host"`
	HostKey      string `json:"host_key"`
	IdentityFile string `json:"identity_file"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, createNode,
		arg.User,
		arg.Host,
		arg.HostKey,
		arg.IdentityFile,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.Host,
		&i.HostKey,
		&i.IdentityFile,
		&i.CreatedAt,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, user, host, host_key, identity_file, created_at FROM nodes WHERE id = ?
`

func (q *Queries) GetNode(ctx context.Context, id int64) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.Host,
		&i.HostKey,
		&i.IdentityFile,
		&i.CreatedAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, user, host, host_key, identity_file, created_at FROM nodes ORDER BY id
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.User,
			&i.Host,
			&i.HostKey,
			&i.IdentityFile,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
